const constants = {
  overlay: {
    translationServers: {
      MOJANG: {
        props: {
          ID: "MOJANG",
          title: "Mojang",
          subtitle: "Official (100-250ms Response Time » Very Fast)",
        },
        URLs: {
          UUID: "https://api.mojang.com/users/profiles/minecraft/{USERNAME}",
          username: "https://api.mojang.com/user/profile/{UUID}",
        },
        paths: {
          UUID: "$.id",
          username: "$.name",
        },
      },
      MOWOJANG: {
        props: {
          ID: "MOWOJANG",
          title: "Mowojang",
          subtitle: "3rd Party (150-250ms Response Time » Fast)",
        },
        URLs: {
          UUID: "https://mowojang.matdoes.dev/{USERNAME}",
          username: "https://mowojang.matdoes.dev/{UUID}",
        },
        paths: {
          UUID: "$.id",
          username: "$.name",
        },
      },
      PLAYERDB: {
        props: {
          ID: "PLAYERDB",
          title: "PlayerDB",
          subtitle: "3rd Party (300-500ms Response Time » Decent)",
        },
        URLs: {
          UUID: "https://playerdb.co/api/player/minecraft/{USERNAME}",
          username: "https://playerdb.co/api/player/minecraft/{UUID}",
        },
        paths: {
          UUID: "$.data.player.id",
          username: "$.data.player.username",
        },
      },
      ASHCON: {
        props: {
          ID: "ASHCON",
          title: "Ashcon",
          subtitle: "3rd Party (1000-2000ms Response Time » Slow)",
        },
        URLs: {
          UUID: "https://api.ashcon.app/mojang/v2/user/{USERNAME}",
          username: "https://api.ashcon.app/mojang/v2/user/{UUID}",
        },
        paths: {
          UUID: "$.uuid",
          username: "$.username",
        },
      },
      CUSTOM: {
        props: {
          ID: "CUSTOM",
          title: "Custom",
          subtitle: "Your own Translation Server",
        },
      },
    },
    themes: {
      DARK: "dark",
      LIGHT: "light",
      SAKURA: "sakura",
      KAWAII: "kawaii",
      CUSTOM: "custom",
    },
    supportedClients: {
      DEFAULT: "Default/Vanilla",
      LUNAR: "Lunar",
      BADLION: "Badlion",
      CUSTOM: "Custom",
    },
    supportedModes: {
      hypixel: {
        BEDWARS: "Bedwars",
        SKYWARS: "Skywars",
        DUELS: "Duels",
        MURDER_MYSTERY: "Murder Mystery",
      },
      bedwars: {
        OVERALL: "Overall",
        CORES: "Cores",
        SOLO: "Solo",
        DOUBLES: "Doubles",
        THREES: "Threes",
        FOURS: "Fours",
        "4V4": "4v4",
      },
      skywars: {
        OVERALL: "Overall",
        SOLO: "Solo",
        DOUBLES: "Doubles",
      },
      duels: {
        OVERALL: "Overall",
      },
      murderMystery: {
        OVERALL: "Overall",
        CLASSIC: "Classic",
        DOUBLE_UP: "Double Up",
        INFECTION: "Infection",
        ASSASSINS: "Assassins",
      },
    },
    supportedColumns: {
      hypixel: {
        LEVEL: "Network Level",
        KARMA: "Network Karma",
        ACHIEVEMENT_POINTS: "Achievement Points",
      },
      bedwars: {
        LEVEL: "Level",
        WINSTREAK: "Winstreak",
        WINS: "Wins",
        LOSSES: "Losses",
        WLR: "Win/Loss Ratio",
        FINAL_KILLS: "Finalkills",
        FINAL_DEATHS: "Finaldeaths",
        FKDR: "Final-kill/death Ratio",
        KILLS: "Kills",
        DEATHS: "Deaths",
        KDR: "Kill/Death Ratio",
        BEDS_BROKEN: "Beds broken",
        BEDS_LOST: "Beds lost",
        BBLR: "Beds-broken/lost Ratio",
      },
      skywars: {
        LEVEL: "Level",
        WINS: "Wins",
        LOSSES: "Losses",
        WLR: "Win/Loss Ratio",
        KILLS: "Kills",
        DEATHS: "Deaths",
        KDR: "Kill/Death Ratio",
      },
      duels: {
        WINSTREAK: "Winstreak",
        WINS: "Wins",
        LOSSES: "Losses",
        WLR: "Win/Loss Ratio",
        KILLS: "Kills",
        DEATHS: "Deaths",
        KDR: "Kill/Death Ratio",
      },
      murderMystery: {
        WINS: "Wins",
        LOSSES: "Losses",
        WLR: "Win/Loss Ratio",
        KILLS: "Kills",
        DEATHS: "Deaths",
        KDR: "Kill/Death Ratio",
        TIMES_HERO: "Times Hero",
        MURDERER_CHANCE: "Murderer Chance",
        DETECTIVE_CHANCE: "Detective Chance",
      },
    },
    headers: {
      hypixel: {
        LEVEL: { title: "Network Level", align: "center", key: "player.level", width: "10%" },
        KARMA: { title: "Network Karma", align: "center", key: "player.karma", width: "10%" },
        ACHIEVEMENT_POINTS: { title: "Achievement Points", align: "center", key: "player.achievementPoints", width: "10%" },
      },
      bedwars: {
        LEVEL: { title: "Level", align: "center", key: "player.stats.Bedwars.level", width: "10%" },
        WINSTREAK: { title: "Winstreak", align: "center", key: "player.stats.Bedwars.{MODE}.winstreak", width: "6%" },
        WINS: { title: "Wins", align: "center", key: "player.stats.Bedwars.{MODE}.wins", width: "10%" },
        LOSSES: { title: "Losses", align: "center", key: "player.stats.Bedwars.{MODE}.losses", width: "10%" },
        WLR: { title: "WLR", align: "center", key: "player.stats.Bedwars.{MODE}.WLR", width: "10%" },
        FINAL_KILLS: { title: "Finalkills", align: "center", key: "player.stats.Bedwars.{MODE}.finalKills", width: "10%" },
        FINAL_DEATHS: { title: "Finaldeaths", align: "center", key: "player.stats.Bedwars.{MODE}.finalDeaths", width: "10%" },
        FKDR: { title: "FKDR", align: "center", key: "player.stats.Bedwars.{MODE}.FKDR", width: "10%" },
        KILLS: { title: "Kills", align: "center", key: "player.stats.Bedwars.{MODE}.kills", width: "10%" },
        DEATHS: { title: "Deaths", align: "center", key: "player.stats.Bedwars.{MODE}.deaths", width: "10%" },
        KDR: { title: "KDR", align: "center", key: "player.stats.Bedwars.{MODE}.KDR", width: "10%" },
        BEDS_BROKEN: { title: "Beds broken", align: "center", key: "player.stats.Bedwars.{MODE}.bedsBroken", width: "10%" },
        BEDS_LOST: { title: "Beds lost", align: "center", key: "player.stats.Bedwars.{MODE}.bedsLost", width: "10%" },
        BBLR: { title: "BBLR", align: "center", key: "player.stats.Bedwars.{MODE}.BBLR", width: "10%" },
      },
      skywars: {
        LEVEL: { title: "Level", align: "center", key: "player.stats.Skywars.level", width: "10%" },
        WINS: { title: "Wins", align: "center", key: "player.stats.Skywars.{MODE}.wins", width: "10%" },
        LOSSES: { title: "Losses", align: "center", key: "player.stats.Skywars.{MODE}.losses", width: "10%" },
        WLR: { title: "WLR", align: "center", key: "player.stats.Skywars.{MODE}.WLR", width: "10%" },
        KILLS: { title: "Kills", align: "center", key: "player.stats.Skywars.{MODE}.kills", width: "10%" },
        DEATHS: { title: "Deaths", align: "center", key: "player.stats.Skywars.{MODE}.deaths", width: "10%" },
        KDR: { title: "KDR", align: "center", key: "player.stats.Skywars.{MODE}.KDR", width: "10%" },
      },
      duels: {
        WINSTREAK: { title: "Winstreak", align: "center", key: "player.stats.Duels.{MODE}.winstreak", width: "6%" },
        WINS: { title: "Wins", align: "center", key: "player.stats.Duels.{MODE}.wins", width: "10%" },
        LOSSES: { title: "Losses", align: "center", key: "player.stats.Duels.{MODE}.losses", width: "10%" },
        WLR: { title: "WLR", align: "center", key: "player.stats.Duels.{MODE}.WLR", width: "10%" },
        KILLS: { title: "Kills", align: "center", key: "player.stats.Duels.{MODE}.kills", width: "10%" },
        DEATHS: { title: "Deaths", align: "center", key: "player.stats.Duels.{MODE}.deaths", width: "10%" },
        KDR: { title: "KDR", align: "center", key: "player.stats.Duels.{MODE}.KDR", width: "10%" },
      },
      murderMystery: {
        WINS: { title: "Wins", align: "center", key: "player.stats.MurderMystery.{MODE}.wins", width: "10%" },
        LOSSES: { title: "Losses", align: "center", key: "player.stats.MurderMystery.{MODE}.losses", width: "10%" },
        WLR: { title: "WLR", align: "center", key: "player.stats.MurderMystery.{MODE}.WLR", width: "10%" },
        KILLS: { title: "Kills", align: "center", key: "player.stats.MurderMystery.{MODE}.kills", width: "10%" },
        DEATHS: { title: "Deaths", align: "center", key: "player.stats.MurderMystery.{MODE}.deaths", width: "10%" },
        KDR: { title: "KDR", align: "center", key: "player.stats.MurderMystery.{MODE}.KDR", width: "10%" },
        TIMES_HERO: { title: "Times Hero", align: "center", key: "player.stats.MurderMystery.{MODE}.timesHero", width: "6%" },
        MURDERER_CHANCE: { title: "Murderer Chance", align: "center", key: "player.stats.MurderMystery.murdererChance", width: "6%" },
        DETECTIVE_CHANCE: { title: "Detective Chance", align: "center", key: "player.stats.MurderMystery.detectiveChance", width: "6%" },
      },
    },
  },
  hypixel: {
    games: {
      QUAKECRAFT: "Quakecraft",
      SKYCLASH: "SkyClash",
      BUILD_BATTLE: "BuildBattle",
      UHC: "UHC Champions",
      LEGACY: "Classic Games",
      SKYBLOCK: "Skyblock",
      HOUSING: "Housing",
      MCGO: "Cops and Crims",
      WOOL_GAMES: "Wool Wars",
      SURVIVAL_GAMES: "Blitz Survival Games",
      BATTLEGROUND: "Warlords",
      MURDER_MYSTERY: "Murder Mystery",
      ARCADE: "Arcade",
      ARENA: "Arena Brawl",
      TNTGAMES: "TNT Games",
      WALLS: "Walls",
      SKYWARS: "Skywars",
      VAMPIREZ: "VampireZ",
      PROTOTYPE: "Prototype",
      WALLS3: "Mega Walls",
      BEDWARS: "Bedwars",
      PAINTBALL: "Paintball",
      SUPER_SMASH: "Smash Heroes",
      SMP: "SMP",
      REPLAY: "Replay",
      TRUE_COMBAT: "Crazy Walls",
      PIT: "Pit",
      SPEED_UHC: "Speed UHC",
      DUELS: "Duels",
      GINGERBREAD: "Turbo Kart Racers",
    },
  },
};

export default constants;
